// src/simpleWordMap.js
// Map of harder words or phrases -> simpler alternative.
// Keys are lowercase. Preserve the user's capitalization when you display suggestions.
export const SIMPLE_WORD_MAP = {
  "accompany": "go with",
  "accomplish": "do",
  "accordingly": "so",
  "accrue": "gain",
  "accurate": "right",
  "additional": "more",
  "address": "discuss",
  "adjacent to": "next to",
  "advantageous": "helpful",
  "adversely impact": "hurt",
  "advise": "recommend",
  "afford an opportunity": "allow",
  "aircraft": "plane",
  "allocate": "divide",
  "anticipate": "expect",
  "a number of": "some",
  "apparent": "clear",
  "appreciable": "many",
  "appropriate": "proper",
  "approximately": "about",
  "as a means of": "to",
  "ascertain": "find out",
  "assist": "help",
  "assistance": "help",
  "assistance with": "help with",
  "attain": "meet",
  "attempt": "try",
  "at the present time": "now",
  "benefit": "help",
  "capability": "ability",
  "close proximity": "near",
  "combined": "joint",
  "commence": "begin",
  "comply with": "follow",
  "comprise": "include",
  "concerning": "about",
  "consequently": "so",
  "consolidate": "combine",
  "constitutes": "is",
  "contains": "has",
  "convene": "meet",
  "currently": "now",
  "deem": "consider",
  "delete": "cut",
  "demonstrate": "show",
  "depart": "leave",
  "designate": "appoint",
  "desire": "want",
  "determine": "decide",
  "disclose": "show",
  "discontinue": "stop",
  "disseminate": "send",
  "due to the fact that": "because",
  "during the period": "during",
  "effect modifications": "make changes",
  "elect": "choose",
  "eliminate": "remove",
  "employ": "use",
  "encounter": "meet",
  "endeavor": "try",
  "ensure": "make sure",
  "equitable": "fair",
  "establish": "set up",
  "evident": "clear",
  "expedite": "speed up",
  "expeditious": "quick",
  "expend": "spend",
  "expertise": "skill",
  "expiration": "end",
  "facilitate": "help",
  "feasible": "workable",
  "finalize": "finish",
  "forfeiture": "loss",
  "for the purpose of": "to",
  "forward": "send",
  "frequently": "often",
  "function": "role",
  "furnish": "send",
  "has a requirement for": "needs",
  "herein": "here",
  "heretofore": "until now",
  "however": "but",
  "identify": "find",
  "immediately": "at once",
  "impacted": "affected",
  "implement": "start",
  "in accordance with": "under",
  "in addition": "also",
  "in an effort to": "to",
  "in a timely manner": "on time",
  "inception": "start",
  "incumbent upon": "must",
  "indicate": "show",
  "initial": "first",
  "initiate": "start",
  "in lieu of": "instead of",
  "in order to": "to",
  "in regard to": "about",
  "in relation to": "about",
  "in the event that": "if",
  "in the near future": "soon",
  "in view of": "since",
  "is authorized to": "may",
  "is responsible for": "handles",
  "it appears": "seems",
  "it is essential": "must",
  "liaison": "discussion",
  "maintain": "keep",
  "methodology": "method",
  "minimize": "reduce",
  "modify": "change",
  "monitor": "check",
  "necessitate": "need",
  "notify": "tell",
  "notwithstanding": "despite",
  "numerous": "many",
  "objective": "goal",
  "observe": "see",
  "on a regular basis": "routinely",
  "operate": "run",
  "optimum": "best",
  "option": "choice",
  "parameters": "limits",
  "participate": "take part",
  "perform": "do",
  "permit": "allow",
  "pertaining to": "about",
  "portion": "part",
  "possess": "have",
  "practicable": "practical",
  "preclude": "prevent",
  "previous": "earlier",
  "prior to": "before",
  "proceed": "go ahead",
  "procure": "get",
  "proficiency": "skill",
  "promulgate": "publish",
  "provide": "give",
  "provided that": "if",
  "purchase": "buy",
  "pursuant to": "under",
  "regarding": "about",
  "relocate": "move",
  "remuneration": "payment",
  "render": "give",
  "represents": "is",
  "request": "ask",
  "requirement": "need",
  "reside": "live",
  "retain": "keep",
  "selection": "choice",
  "similar to": "like",
  "solicit": "ask for",
  "state-of-the-art": "latest",
  "submit": "send",
  "subsequent to": "after",
  "sufficient": "enough",
  "terminate": "end",
  "therefore": "so",
  "there is": "omit",
  "there are": "omit",
  "timely": "prompt",
  "transmit": "send",
  "under the provisions of": "under",
  "until such time as": "until",
  "utilize": "use",
  "validation": "confirmation",
  "validate": "confirm",
  "viable": "workable",
  "whereas": "because",
  "with reference to": "about",
  "with regard to": "about",
  "witnessed": "saw",
  // Extras commonly flagged in health, gov, and benefits writing:
  "advance planning": "planning",
  "aggregate": "total",
  "applicant": "person applying",
  "assess": "judge",
  "commence services": "start services",
  "component": "part",
  "disburse": "pay",
  "endeavor to": "try to",
  "expended": "spent",
  "implement a program": "start a program",
  "individuals": "people",
  "on a monthly basis": "monthly",
  "per annum": "per year",
  "prior authorization": "pre approval",
  "prohibited": "not allowed",
  "receive benefits": "get benefits",
  "remainder": "rest",
  "renumeration": "payment", // common misspelling
  "requisition": "request",
  "subsequently": "later",
  "terminate services": "end services",
  "utilization": "use"
};
